### ISSUE TITLE
weakSelf

### ISSUE THREAD

**Issue by leebarringer** [mmackh/IPDFCameraViewController#10]
Hello, love your demo, I cannot get the code to work in my project. Basically I get "__weak typeof(self) weakSelf = self;" causing a build error in IPDFCamerViewController.m

use of undeclared identifier weakSelf. My compiler just doesn't seem to understand the declaration syntax for weakSelf. Do you have any ideas? I'd love to use the code. Thanks

**Comment by mmackh** [comment]
You can try __weak IPDFCameraViewController *weakSelf = self;

**Comment by leebarringer** [comment]
Thank you. Did this and it worked perfectly.
