### ISSUE TITLE
Auto selection / cropping the image

### ISSUE THREAD

**Issue by Himanidineshgarg** [mmackh/IPDFCameraViewController#11]
I want auto selection/ cropping in the project .Can you please explain the methods/ways that are used to implement the same?

I have change the value of imageDedectionConfidence value to 1 but nothing happens. Can you explain what I need to do?

**Comment by mmackh** [comment]
This is out of the scope of this control. However, my approach was to firstly check if previous detected rectangle points were within the bounds of their predecessor. With each border detection frame being in bounds, I added a + 0.1 to the overall confidence. Once the control reaches a certain confidence, then the rectangle is drawn and the progress indicator is incremented. Once I reach 1.0 on confidence, I automatically triggered the capture.
