### ISSUE TITLE
Flickering Rectangle Selection

### ISSUE THREAD

**Issue by leebarringer** [mmackh/IPDFCameraViewController#12]
Hello,

I'm trying to use your control (excellent work!) to scan in an image of document with lots of well defined margins, lines and boxes within it.

As you can image this causes the automatic rectangle detector to jump and skip all over the place. Is there any simple way of reducing the sensitivity of the control to these - or perhaps also slowing down the rate at which it skips between identified rectangles?

Many thanks,

Lee

**Comment by mmackh** [comment]
Hello Lee, 

this is quite an advanced feature and not within the scope of this control, but I've discussed my approach here: https://github.com/mmackh/IPDFCameraViewController/issues/11

Cheers,
Maximilian
