### ISSUE TITLE
-[UIImage pathExtension]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by rfunk82** [mmackh/IPDFCameraViewController#16]
I implemented your library but every time I take a picture I receive the following error message:

-[UIImage pathExtension]: unrecognized selector sent to instance 0x15f452d90
 *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIImage pathExtension]: unrecognized selector sent to instance 0x15f452d90

This is happening at this line:

UIImageView *captureImageView = [[UIImageView alloc] initWithImage:[UIImage imageWithContentsOfFile:imageFilePath]];

I'm not sure what I'm doing wrong.

Thanks

**Comment by mmackh** [comment]
Have you updated to the latest version? Does the demo project also exhibit this bug?

**Comment by rfunk82** [comment]
I did update to the latest version. Demo works fine. If it helps in any way I was able to fix it doing:

UIImageView *captureImageView = [[UIImageView alloc] initWithImage:(UIImage*)imageFilePath];

but I'm not sure if it will have any "side effects".

**Comment by mmackh** [comment]
Can you please post the whole block of code?

**Comment by rfunk82** [comment]
Thanks for your time!

<pre><code>
- (IBAction)captureButton:(id)sender
{
    __weak typeof(self) weakSelf = self;
    
    [self.cameraViewController captureImageWithCompletionHander:^(NSString *imageFilePath)
     {
         UIImageView *captureImageView = [[UIImageView alloc] initWithImage:(UIImage*)imageFilePath];
         captureImageView.backgroundColor = [UIColor colorWithWhite:0.0 alpha:0.7];
         captureImageView.frame = CGRectOffset(weakSelf.view.bounds, 0, -weakSelf.view.bounds.size.height);
         captureImageView.alpha = 1.0;
         captureImageView.contentMode = UIViewContentModeScaleAspectFit;
         captureImageView.userInteractionEnabled = YES;
         [weakSelf.view addSubview:captureImageView];
         
         UITapGestureRecognizer *dismissTap = [[UITapGestureRecognizer alloc] initWithTarget:weakSelf action:@selector(dismissPreview:)];
         [captureImageView addGestureRecognizer:dismissTap];
         
         [UIView animateWithDuration:0.7 delay:0.0 usingSpringWithDamping:0.8 initialSpringVelocity:0.7 options:UIViewAnimationOptionAllowUserInteraction animations:^
          {
              captureImageView.frame = weakSelf.view.bounds;
          } completion:nil];
     }];
}

</code></pre>

**Comment by MyOnlyOnlySunshine** [comment]
hi I use your IPDFCameraViewController, but i don't know how to resolve this problems .i didn't use xib,I write all of the views By myself. 
 the issues happened in  [self.cameraViewController setupCameraView];
 error message : Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[AVCaptureVideoDataOutput setSampleBufferDelegate:queue:] - NULL sampleBufferCallbackQueue passed.'
 coule you help me?
thanks...

**Comment by mmackh** [comment]
Are the camera permissions enabled?

**Comment by MyOnlyOnlySunshine** [comment]
yes  I use iPhone6s to test demo ...

**Comment by gklka** [comment]
I think the recent version has changed the return type of the `captureImageWithCompletionHandler` from `NSString *` of path to `id` (of image data). You should modify the demo code to work like this:

```
    [self.cameraViewController captureImageWithCompletionHander:^(id image)
    {
        UIImageView *captureImageView = [[UIImageView alloc] initWithImage:image];

```

**Comment by mmackh** [comment]
Please clone and run the project from scratch. There might be something wrong with your code. As @gklka mentioned, the completion handler changed its return type from Data to a String.
