### ISSUE TITLE
Differences between this project and MAImagePickerController

### ISSUE THREAD

**Issue by jamieomatthews** [mmackh/IPDFCameraViewController#18]
If I might ask - why did you switch from using OpenCV to writing this stuff natively?  I'm interested in doing this cross platform, so I'm curious.  I didn't see an explanation of what changed after the deprecation, but I did notice that OpenCV is no longer a dependency.

**Comment by mmackh** [comment]
Dropping cruft, better algorithms, faster performance, way easier to compile.
