### ISSUE TITLE
Images still showing upside down.

### ISSUE THREAD

**Issue by Jkurbs** [mmackh/IPDFCameraViewController#28]
Hi, i've update the library but my images are still showing upside down. Btw thank you for the library :).

**Comment by mmackh** [comment]
Via which update method?

**Comment by Jkurbs** [comment]
Pod update

**Comment by mmackh** [comment]
I don't maintain the pod file maybe there need to be some changes made

**Comment by Jkurbs** [comment]
Okay but how can I make it work? Thanks

**Comment by Jkurbs** [comment]
Do I need to install it manually?

**Comment by mmackh** [comment]
Yes please try

**Comment by Jkurbs** [comment]
Still not working for me  :(. Do you have any suggestions? Thank you

**Comment by mmackh** [comment]
Did hou try the demo project?

**Comment by gklka** [comment]
Same problem here. The demo project works fine, I think you have fixed the issue. Can I ask, when do you want to release a new version on CocoaPods?

**Comment by Jkurbs** [comment]
Right now i'm using this function to rotate the image

 `func rotated(by degrees: Double) -> UIImage? {
        guard let cgImage = self.cgImage else { return nil }
        
        let transform = CGAffineTransform(rotationAngle: degrees.toRadians())
        var rect = CGRect(origin: .zero, size: self.size).applying(transform)
        rect.origin = .zero
        
        let renderer = UIGraphicsImageRenderer(size: rect.size)
        return renderer.image { renderContext in
            renderContext.cgContext.translateBy(x: rect.midX, y: rect.midY)
            renderContext.cgContext.rotate(by: degrees.toRadians())
            renderContext.cgContext.scaleBy(x: 1.0, y: -1.0)
            
            let drawRect = CGRect(origin: CGPoint(x: -self.size.width/2, y: -self.size.height/2), size: self.size)
            renderContext.cgContext.draw(cgImage, in: drawRect)
        }
    }
`

**Comment by mmackh** [comment]
#31 Pod update needed
