### ISSUE TITLE
instapdf and cordova

### ISSUE THREAD

**Issue by rzorgani** [mmackh/IPDFCameraViewController#29]
Hello, 
I want to implement your solution instapdf in my example with cordova.
Below are the steps that I made
cordova create NativeCamera fr.test.nativecam NativeCamera
cd NativeCamera
cordova platform add ios
cd platforms/ios/
pod init
then I add  pod "IPDFCameraViewController" to my pod file
pod install
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod
installed.
Next, I add IPDFCameraViewController/IPDFCameraViewController.h andIPDFCameraViewController/IPDFCameraViewController.m
When I wnt build my application I have this error
diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
Ticket: https://instapdf.freshdesk.com/helpdesk/tickets/20

**Comment by mmackh** [comment]
Sorry this is not supported in this library
