### ISSUE TITLE
iOS7 - what calls are not supported? Any way, how to support iOS 7?

### ISSUE THREAD

**Issue by kutakmir** [mmackh/IPDFCameraViewController#4]
Hey, what feature prevents the framework from iOS 7 deployment?

**Comment by mmackh** [comment]
A pretty essential component CIRectangleFeature, is iOS8 only. It detects a rectangle within an Image. Without it, there's no Autocrop and automatic perspective correction.

**Comment by colasjojo** [comment]
Hi @mmackh. If I leave `enableBorderDetection` to `NO`, will it be ok with iOS7?

**Comment by mmackh** [comment]
I don't have a device to test with - please try and report back.

**Comment by Lejdborg** [comment]
It doesn't work completely with just setting `enableBorderDetection` to `NO`, but it's easy to get it working. You have a blur view that needs to be removed as well (if I recall correctly).
