### ISSUE TITLE
Use of UIView.bounds from the background thread

### ISSUE THREAD

**Issue by xjki** [mmackh/IPDFCameraViewController#42]
I found with thread checker that (at least on iOS11) method
`-(void)captureOutput:(AVCaptureOutput *)captureOutput didOutputSampleBuffer:(CMSampleBufferRef)sampleBuffer fromConnection:(AVCaptureConnection *)connection`
is used on the background thread. 

That probably can explaid some of the accidental crashes because method uses [self.bounds](https://github.com/mmackh/IPDFCameraViewController/blob/55b731d529a32de8ff50594fc169acae9c8bc60a/IPDFCameraViewController/IPDFCameraViewController.m#L213) that should be called from main thread only.

**Comment by mmackh** [comment]
To resolve this issue, I'd declare a property (cachedBounds)  which can be access from background threads and is updated in -(void)layoutSubviews

**Comment by mmackh** [comment]
Pull requests welcome to implement this behaviour or a fix for this warning

**Comment by shoaibhassanWhizpool** [comment]
@mmackh why have you create property of  cachedBounds.and what type of object is this...can you please share complete code of this methods causing thread warning and some time shows black screen on iPad.
