### ISSUE TITLE
iOS11: Use Vision for edge detection

### ISSUE THREAD

**Issue by marbetschar** [mmackh/IPDFCameraViewController#44]
Use iOS11 new Vision framework for better & speedier edge detection. See the all new notes app document scanner as an example.

https://developer.apple.com/documentation/vision

**Comment by marbetschar** [comment]
@mmackh is the integration of iOS 11 Vision something you'd consider for `IPDFCameraViewController`?

**Comment by mmackh** [comment]
Hi - sorry currently no time to update this library. Also no plans on implementing the vision framework due to backwards compatibility and observing that it isn't significantly faster / better IMO.
