### ISSUE TITLE
BSXPCMessage received error for message: Connection interrupted

### ISSUE THREAD

**Issue by tangyorangesour** [mmackh/IPDFCameraViewController#6]
Getting this error while trying to test the application. 

I'm using iOS 8.3 and Xcode 6.3 

Also the picture is not getting saved as cropped image and I've tried on many different types of documents (cards, passports, receipts..etc.) as this check is never successful. 
[self.cameraViewController captureImageWithCompletionHander:^(id data)

**Comment by mmackh** [comment]
This is an issue with iOS 8 and CoreImage, and should not affect operation. As for your second issue, you'll have to manually save the data to your photo album or otherwise.

**Comment by dama2716588** [comment]
iOS 8.3 and Xcode 8.0 beta 3 (8S174q) also has this issue !
