### ISSUE TITLE
Auto select /crop the image

### ISSUE THREAD

**Issue by pepperss** [mmackh/IPDFCameraViewController#7]
In instaPDF app you have progress bar which  crop the image automatically without pressing the capture button. I want to achieve that effect but I am not able to do that

**Comment by mmackh** [comment]
The way I did it was to create an additional delegate that passed through the detection confidence normalised from 0.0 to 1.0 every time ```-(void)captureOutput:(AVCaptureOutput *)captureOutput didOutputSampleBuffer:(CMSampleBufferRef)sampleBuffer fromConnection:(AVCaptureConnection *)connection
```
ran

**Comment by Himanidineshgarg** [comment]
Can you describe it more? Actually i am not able to implement the same?
