### ISSUE TITLE
CocoaPods

### ISSUE THREAD

**Issue by alexruperez** [mmackh/IPDFCameraViewController#8]
https://guides.cocoapods.org/making/specs-and-specs-repo.html

**Comment by barrettj** [comment]
I've got one setup to my fork (currently only implements podspec and license file, no other differences) if you'd like to take a look:
https://github.com/barrettj/IPDFCameraViewController

**Comment by alexruperez** [comment]
@barrettj seems correct, waiting pull request and merge. :)

**Comment by barrettj** [comment]
Wouldn't want to straight up merge as it's pointing directly to my fork (so I can use it in my private spec repo) :P

**Comment by alexruperez** [comment]
@barrettj 
![D'OH!](http://www.whoateallthepies.tv/wp-content/uploads/2013/09/doh.gif)

**Comment by mmackh** [comment]
Any pull request welcome that adds CocoaPods. I'm not a user myself.

**Comment by lmirosevic** [comment]
+1

**Comment by michaelbina** [comment]
Any progress on this?  I'd like to integrate and would prefer to use cocoa pods if possible...

**Comment by mmackh** [comment]
No one has submitted a pull request so far, but anyone is welcome to.

**Comment by michaelbina** [comment]
Pull request made.  I followed @barrettj's example and pointed the library to this repo.  Not sure if you already had a higher version assigned but the file is now pointing to 0.0.1.  I can change that if you have a more accurate version.

**Comment by mmackh** [comment]
Thank you @michaelbina for your contribution. Enjoy cocoapods everyone 👍

**Comment by michaelbina** [comment]
I noticed after I submitted the pull request that this does not work unless there is a version tagged "0.0.1" in the repo.  I fixed this for myself by temporarily pointing back to @barrettj's repo, but for future users of this repo, it would be nice if that could get done.  Thanks for merging so quick.

**Comment by mmackh** [comment]
Ok, I've added the tag. Please report back if it works for you.

**Comment by mmackh** [comment]
Seems like no one is having an issue with this atm. Will close for now.
