### ISSUE TITLE
Memory issues

### ISSUE THREAD

**Issue by fvvliet** [mmackh/IPDFCameraViewController#9]
Hello Maximilian,

I am using this very nice cameraviewcontroller in an app but keep getting memory warnings and crashes, the crash logs mention [vm-pageshortage] reasons. The other error that keeps popping up is 'BSXPCMessage received error for message: Connection interrupted'. Any idea what could be the reason for this ? I am running on iPhone & iPad with iOS 8.4.

Thanks
Frank

**Comment by semerda** [comment]
Ditto. Seeing a lot of crashes in:
[IPDFCameraViewController setupCameraView]
[IPDFCameraViewController start]

**Comment by andho** [comment]
We also get Crash and slow down of the app when we open and close the IPDFCameraViewController a few times too (around 10 times).

**Comment by mmackh** [comment]
Latest commit should fix any memory related issues. Let me know if anything else needs tweaking.

**Comment by NahidAshraf** [comment]
There is memory leaks while opening and closing Picker

**Comment by NahidAshraf** [comment]
[IPDFCameraViewController setupCameraView] crashing

**Comment by NahidAshraf** [comment]
BSXPCMessage received error for message: Connection interrupted
